# Generated by Django 6.0.3 on 2026-03-05 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutando'), ('done', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='simulator.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del río (sin espacios)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutando'), ('done', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_excel', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('reaches_json', models.JSONField(blank=True, null=True)),
                ('sources_json', models.JSONField(blank=True, null=True)),
                ('wqdata_json', models.JSONField(blank=True, null=True)),
                ('n_reaches', models.IntegerField(default=1)),
                ('xmon', models.IntegerField(default=6)),
                ('xday', models.IntegerField(default=27)),
                ('xyear', models.IntegerField(default=2012)),
                ('timezonehour', models.IntegerField(default=-5)),
                ('pco2', models.FloatField(default=0.000347)),
                ('dtuser', models.FloatField(default=0.00416666666666667)),
                ('tf', models.FloatField(default=5.0)),
                ('imeth', models.CharField(default='Euler', max_length=10)),
                ('imeth_ph', models.CharField(default='Brent', max_length=10)),
                ('q_cabecera', models.FloatField(default=1.065e-06)),
                ('numelem', models.IntegerField(default=10)),
                ('reach_rates_json', models.JSONField(blank=True, null=True)),
                ('work_dir', models.CharField(blank=True, max_length=500)),
                ('kge_global', models.FloatField(blank=True, null=True)),
                ('kge_by_var_json', models.JSONField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='simulator.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('nombre_vertimiento', models.CharField(blank=True, max_length=200)),
                ('fila_resultado', models.IntegerField(default=0)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='simulator.pipelinerun')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='simulator.simulationrun')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
