# Generated by Django 6.0.3 on 2026-03-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='generar_comparacion',
            field=models.BooleanField(default=True, help_text='Genera gráficas Simulado vs Observado (requiere datos en WQ_DATA más allá de CABECERA)'),
        ),
    ]
